### ISSUE TITLE
Exception on disconnect

### ISSUE THREAD

**Issue by thibp** [genielabs/serialport-lib-dotnet#1]
When I disconnect I have this following Exception :
Unhandled Exception:
System.AggregateException:  ---> System.Threading.Tasks.TaskCanceledException: The Task was canceled
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout) [0x00000] in <filename unknown>:0
  at SerialPortLib.SerialPortInput.Disconnect () [0x00000] in <filename unknown>:0
  at ConsoleApplication1.COMPort.Dispose () [0x00000] in <filename unknown>:0
  at ConsoleApplication1.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
 --> (Inner exception 0) System.Threading.Tasks.TaskCanceledException: The Task was canceled

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException:  ---> System.Threading.Tasks.TaskCanceledException: The Task was canceled
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout) [0x00000] in <filename unknown>:0
  at SerialPortLib.SerialPortInput.Disconnect () [0x00000] in <filename unknown>:0
  at ConsoleApplication1.COMPort.Dispose () [0x00000] in <filename unknown>:0
  at ConsoleApplication1.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
 --> (Inner exception 0) System.Threading.Tasks.TaskCanceledException: The Task was canceled

**Comment by thibp** [comment]
I noticed that it is solved by removing the timeout in the Wait call inside the Disconnect method but still have an issue on Linux when there was a unsuccessful previous connection.
If the previous connection was successful it work with this modification.

**Comment by thibp** [comment]
This seems to be solved by :
public bool Connect()
        {
            Disconnect();
            bool returnValue = Open();
            if (returnValue)
            {
                gotReadWriteError = !returnValue;
                watcherTokenSource = new CancellationTokenSource();
                connectionWatcher = Task.Factory.StartNew(() => ConnectionWatcherTask(watcherTokenSource.Token), watcherTokenSource.Token);
            }
            return returnValue;
        }

public void Disconnect()
        {
            if (connectionWatcher != null)
            {
                watcherTokenSource.Cancel();
                connectionWatcher.Wait();
                if (connectionWatcher != null)
                    connectionWatcher.Dispose();
                connectionWatcher = null;
                watcherTokenSource = null;
            }
            Close();
        }

**Comment by thibp** [comment]
This bug happened when more than 3 unsuccessful connections was made before because the condition of the return value was not there.
You could also include Disconnect in your example page ;)

**Comment by genielabs** [comment]
Hi @thibp, I was not able to reproduce the issue. Can you please provide a more detailed example with steps needed to reproduce it?
Anyway I added try..catch instructions to prevent the **AggregateException**.

**Comment by thibp** [comment]
Hello,
The issue is coming mainly because a Watcher is created even when the connection fails.
Why not use my code?

To reproduce it, you can try run it on a Rapsberry Pi (maybe a Linux debian may work) and try establish about 10-30 unsuccessful connections then a successful connection.
If you are using a Pi you have great chance that you have about 30 serial port not working that you can get with this code (like /dev/tty1, /dev/tty2, /dev/tty3, /dev/tty10, /dev/tty11...) :
String[] ports = SerialPort.GetPortNames();

I don't have the test code but this the workflow :
forach on ports
  Create Serial
  Open it
  WriteData
  Close it (very important).

I also suggest to add the Close function in your example ;)
