### ISSUE TITLE
Unable to use on VS 2010 as it appears to be targetting NET 4.5

### ISSUE THREAD

**Issue by HabitatAus** [genielabs/serialport-lib-dotnet#2]
I tried to use this on VS 2010 and received the following error

Warning	1	The primary reference "SerialPortLib, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0,Profile=Client".	NSP

VS 2010 will only go as high as NET 4.0.

Would you mind making it compatible with 4.0 o that it can be used on VS2010?

Great work by the way, this will be a big help for those using serial ports on Linux using Mono!

Greg

**Comment by genielabs** [comment]
did it.

**Comment by HabitatAus** [comment]
Excellent, thank you for your efforts!

 

I will let you know how it goes!

 

Greg
