### ISSUE TITLE
Setting Data bit?

### ISSUE THREAD

**Issue by Memhave** [genielabs/serialport-lib-dotnet#6]
Hi,
Maybe I've not seen it, but is it possible to set data bit length? I'd like to assume its the default 8, but I would also like to know whether it is possible to change it - if need be.

**Comment by AndrewStewartNZ** [comment]
I'm assuming the StopBits is set the DataBits for you.  Just a different way of setting it.

**Comment by genemars** [comment]
see #5

**Comment by beelzaboot** [comment]
I also need the ability to set the databits property of the underlying serial port class. 

StopBits is different than DataBits.

PR incoming...
